config/routes.rb
Rails.application.routes.draw do
  resources :transcripts, only: [:index, :new, :create, :destroy]

  get 'about' => 'static_pages#about'
  get 'result' => 'static_pages#result'

  root 'transcripts#new'

  resources :transcripts

end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :faculty
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
  has_many :courses
end

app/models/transcript.rb
class Transcript < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # use uploader 'attachment' for this model
  validates :attachment, file_size: { less_than: 1.megabytes, message: 'File should be less than 1mb' }
  def self.get_info(this)
      l = this.attachment_url.split(/\//)
      l[0] = "public"
      path = Rails.root
      l.each {|seg| path = path.join seg}
      reader = PDF::Reader.new(path)
      text = ""
      reader.pages.each {|page| text += page.text}
      text
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/controllers/transcripts_controller.rb
class TranscriptsController < ApplicationController
  include TranscriptsHelper
  def index
    @transcripts = Transcript.all
  end

  def new
    @transcript = Transcript.new
  end

  def create

    @transcript = Transcript.new(transcript_params)
    reader = PDF::Reader.new(transcript_params[:attachment])
    result = reader.text
    if @transcript.save
      redirect_to result_path, notice: "The transcript has been uploaded. #{result}"
    else
      render "new"
    end
  end

  def show
    @transcript = Transcript.find(params[:id])
    @text = Transcript.get_info(@transcript)
  end
  def destroy
    @transcript = Transcript.find(params[:id])
    File.delete(@transcript.attachment_url) if File.exist?(@transcript.attachment_url)
    #fail to remove the directory
    # dir = @transcript.attachment_url.sub(File.basename(@transcript.attachment_url),"")
    # remove_entry_secure(File.basename("/home/gumby/work/ruby.rb"), force = false)
    # dir = "/public"+@transcript.attachment_url.sub(/\/[^\/]*$/,'/')
    # Dir.rmdir(dir)
    @transcript.destroy
    redirect_to transcripts_path, notice:  "The transcript has been deleted."
  end


private
  def transcript_params
    params.require(:transcript).permit(:attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def full_title (title = "")
      baseTitle = "UNSW Degree Tracker"
      if title.empty?
         baseTitle
      else
         "#{title} | #{baseTitle}"
      end
   end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transcripts_helper.rb
module TranscriptsHelper

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://github.com/leon-ng9/UNSW-degree-tracker">UNSW Degree Tracker</a> by Leon and Mark
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "UNSW Degree Tracker", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </div>
</header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>
<h1>About</h1>
<p>This is the about page... FAQ HOMIES</p>

app/views/static_pages/home.html.erb
<h1>UNSW Degree Tracker</h1>
<p>Upload your academic transcript PDF found <a href="https://my.unsw.edu.au/active/studentStatement/statement.pdf" target="_blank">here</a></p>

app/views/static_pages/result.html.erb
<%= provide(:title, "Result") %>
<h1>Result</h1>
<p>This is the results page :3</p>
<%= link_to "All transcripts", transcripts_path %>

app/views/transcripts/create.html.erb
<h1>Transcripts#create</h1>
<p>Find me in app/views/transcripts/create.html.erb</p>

app/views/transcripts/destroy.html.erb
<h1>Transcripts#destroy</h1>
<p>Find me in app/views/transcripts/destroy.html.erb</p>

app/views/transcripts/index.html.erb
<h1>Transcripts#index</h1>
<p>Find me in app/views/transcripts/index.html.erb</p>
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<%= link_to "New Transcript", new_transcript_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Download Link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @transcripts.each do |transcript| %>
      <tr>
        <td><%= link_to "Download Transcript", transcript.attachment_url %></td>
        <td><%= button_to "Delete",  transcript, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transcripts/new.html.erb
<h1>UNSW Degree Tracker</h1>
<p>Upload your academic transcript PDF found on <a href="https://my.unsw.edu.au/" target="_blank">myUNSW</a></p>
<% if !@transcript.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @transcript.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @transcript, html: { multipart: true } do |f| %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Upload", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/transcripts/show.html.erb
<pre><%= @text %></pre>